# Perform a dry-run on pull-requests
name: "PR Review Queue Dry Run"

on:  # yamllint disable-line rule:truthy
  pull_request

jobs:
  lint:
    name: Run all linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Install prerequisites
        run: |
          pip install pre-commit
          sudo apt install aspell
        shell: bash
      - name: Run linters
        run: make lint
        shell: bash

  test:
    name: PR review queue dry run
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/ochosi/pr-review-queue:latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Create PR Review Queue for osbuild/osbuild
        # yamllint disable rule:line-length
        run: |
          python3 pr_review_queue.py --github-token "${{ secrets.GITHUB_TOKEN }}" --queue --org osbuild --repo osbuild --dry-run
        # yamllint enable rule:line-length
        shell: bash
